In [1]:
import numpy as np

In [13]:
def fit(M, P, Q, K, epoch=1000, alpha=0.1, beta=0.02):
    for step in range(epoch):
        for i in range(M.shape[0]):
            for j in range(M.shape[1]):
                if(M[i][j] > 0):
                    P[i] = P[i] + alpha * (M[i][j] - np.dot(P[i],Q[j].T))*Q[j]
                    Q[j] = P[j] + alpha * (M[i][j] - np.dot(P[i],Q[j].T))*P[i]
        loss = 0
        num = 0
        for i in range(M.shape[0]):
            for j in range(M.shape[1]):
                if(M[i][j] >0):
                    num += 1
                    loss += np.power(M[i][j] - np.dot(P[i] , Q[j].T),2)
        loss /= num
        if(loss < 0.01):
            print("converge")
            break
    return P,Q

In [14]:
M = [
     [5,3,0,1],
     [4,0,3,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
 
M = np.array(M)
P = np.random.rand(5,2)
Q = np.random.rand(4,2)
pre_P,pre_Q = fit(M,P,Q,2)
res = np.dot(pre_P,pre_Q.T)
print(res)

[[4.50445854 3.52002185 0.28640355 0.83467201]
 [3.51805473 3.13937292 1.80981931 1.87992506]
 [0.27951868 1.79273913 6.41756006 5.00670457]
 [0.82603684 1.84575163 4.93167883 3.93065588]
 [0.21297185 1.40205591 5.03654644 3.92842673]]
